### ISSUE TITLE
Add all scs components to the docs and display them on the overview map 

### ISSUE THREAD

**Issue by maxwolfs** [SovereignCloudStack/docs#136]
For the architectural overview of the sovereign cloud stack we need all components that lie within the scs org with at least one individual markdown file in this repository. 

You can see the current state on the staging branch: https://docs-staging.scs.community/docs
<img width="990" alt="Bildschirmfoto 2024-01-31 um 11 27 48" src="https://github.com/SovereignCloudStack/docs/assets/28341836/032cb49b-7dae-4578-91da-aa1f7931e302">

This being built from this branch/PR: https://github.com/SovereignCloudStack/docs/pull/109

The graphic is being rendered from [this json ](https://github.com/SovereignCloudStack/docs/pull/109/files#diff-4bac13eb1143c7440f5e64bfd513e58911587be82347d3145aa5693ad6a74001) from the same branch.

It needs more content that already exists but is not visible.

**To-do**

Add docs of the following components/repositories (at least one markdown file within the docs)

- [x] Container Registry (container layer)
- [x] Monitoring (ops layer)
- [x] Cluster stacks (container layer) @matofeder & @jschoone 

Still to discuss is:

* If and how to add further upstream projects.
* Which labels are helpful? (Mandatory/Optional are categories of the standards, not the Ref.Impl.)

**Comment by scoopex** [comment]
Probably missing: Storage Layer, Monitoring Setup (Prometheus, Thanos, ...), Log Aggregation, Asset Managment (Netbox)

**Comment by maxwolfs** [comment]
> * Probably missing as a dedicated box : Storage Layer
>   
>   * Ceph RGW Object Storage
>   * Ceph as Storage layer
> * Components in the Ops Layer
>   
>   * Monitoring Setup (Prometheus, Thanos, ...)
>   * Log Aggregation
>   * Asset Managment (Netbox)
>   * Testbed (Run the cloud environment in a virtualized environment for training/testing/development)
>   * CIAB (Run the cloud environment on a single system for training/testing/development)

As discussed on monday I will create an Issue for Ceph related topics and assign @jschoone for that.
Isn't Monitoring covered by https://github.com/SovereignCloudStack/docs/pull/144 ?
Testbed and CIAB are already in the IaaS Layer's guides: https://docs.scs.community/docs/iaas/guides/deploy-guide/examples/

Little bit hidden but this PR with the new introduction places them more prominent on the operator docs introduction.
