### ISSUE TITLE
Epic: Improve KaaS documentation

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/docs#232]
For R7 we need better access to the docs of all the KaaS components.

Tasks:

- [x] #224
- [x] #225
- [ ] #226
- [x] #227
- [x] #228
- [ ] #229
- [ ] #230 
- [x] csctl https://github.com/SovereignCloudStack/csctl/issues/149
- [ ] Cluster Gen https://github.com/SovereignCloudStack/cluster-gen/issues/11
- [x] Switch Cluster-Stacks and k8s-cluster-api-provider in https://docs.scs.community/docs/category/components-1
- [x] Make the linter happy

**Comment by mbuechse** [comment]
Should this really be counted as closed? It seems that some tasks are still pending.
